service: user
useDotenv: true

plugins:
#  - serverless-tscpaths
  - serverless-esbuild
  - serverless-offline
#  - serverless-plugin-warmup

provider: ${file(_provider.yml)}

functions:
  - ${file(src/components/common/functions.yml)}
  - ${file(src/components/user/functions.yml)}

custom:
  tscpaths:
    tsconfigPath: tsconfig.json
  esbuild:
    bundle: true
    minify: false

resources:
  Resources:
    NewSQSQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: user.fifo
        FifoQueue: true
#        DeduplicationScope: messageGroup
#        FifoThroughputLimit: perMessageGroupId
    EventLogTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: event-log
        AttributeDefinitions:
          - AttributeName: pkey
            AttributeType: S
          - AttributeName: version
            AttributeType: N
        KeySchema:
          - AttributeName: pkey
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    UsersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: user-projection
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: email
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: username
            KeySchema:
                - AttributeName: username
                  KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

